version: "3.8"
services:

  stixgen:
    image: my/flaskstixgen
    container_name: stixgen
    hostname: stixgen
    ports:
      - "127.0.0.1:5151:5000"
    networks:
      - stixgen
    restart: unless-stopped

networks:
  stixgen:
    name: stixgen

